package net.ririfa.bulletinboard.gui

enum class GUIState() {
    MAIN_BOARD,
    NEW_POST,
    EDIT_POST,
    MY_POSTS,
    ALL_POSTS,
    DELETED_POSTS,
    SETTINGS,

    EDIT_POST_SELECTION,
    DELETE_POST_SELECTION,
    DELETE_POST_OTHERS_SELECTION,
    RESTORE_POST_SELECTION,
    DELETE_POST_PERMANENTLY_SELECTION,

    CONFIRM_SAVE_POST,
    CONFIRM_SAVE_EDIT
}